name: ci

on:
  push:
  pull_request:
    branches: [ main ]

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:workflow

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check
      # - 
      #   name: Build and export to Docker
      #   uses: docker/build-push-action@v6
      #   with:
      #     load: true
      #     tags: ${{ env.TEST_TAG }}
      # - 
      #   name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
      -
        name: Set short commit id
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}-${{ env.SHORT_SHA }}

      - run: echo "✅ All tests have passed successfully."

      - run: |
          IMAGE_TAG="${{ env.LATEST_TAG }}-${{ env.SHORT_SHA }}"
          echo "The image is available at: $IMAGE_TAG"
